# 本节主要内容
- 矩阵乘法
- 矩阵的逆

## 矩阵乘法
- 矩阵相乘的维度条件，假如A矩阵形状为(m,n)则B矩阵的形状必须是(n,p),注意n必须相等，相乘后，矩阵形状为(m,p)
- 求法1（常规）：AB=C，则$C_{34} = (row 3 of A).(columns 4 of B)$
- 求法2（用列）：矩阵乘法可以看成是矩阵和列向量相乘后得到,可以参考上一节的公式，例子:$\left[\begin{matrix} 1&2&7\\3&4&6\\2&1&3 \end{matrix}\right] \left[\begin{matrix} 1&3\\2&1\\1&4 \end{matrix}\right]= \left[\begin{matrix}{\left[\begin{matrix} 1\\3\\2 \end{matrix}\right]*1+\left[\begin{matrix} 2\\4\\1 \end{matrix}\right]*2+\left[\begin{matrix} 7\\6\\3 \end{matrix}\right]*1}&,{\left[\begin{matrix} 1\\3\\2 \end{matrix}\right]*3+\left[\begin{matrix} 2\\4\\1 \end{matrix}\right]*1+\left[\begin{matrix} 7\\6\\3 \end{matrix}\right]*4}\end{matrix}\right] = \left[\begin{matrix} 12&33\\17&37\\7&19 \end{matrix}\right]$
- 求法3（用行）：矩阵乘法可以看成是行向量和矩阵相乘后得到,可以参考上一节的公式，例子:方法类比求法二，参考上一节公式，此处不多做陈述
- 求法4（用列乘以行）:列1乘以行一，列二乘以行而再相加，$\left[\begin{matrix}2&7\\3&8\\4&9 \end{matrix}\right] \left[\begin{matrix}1&6\\0&0 \end{matrix}\right] = \left[\begin{matrix}2\\3\\4 \end{matrix}\right]\left[\begin{matrix}1&6 \end{matrix}\right] + \left[\begin{matrix}7\\8\\9 \end{matrix}\right] \left[\begin{matrix}0&0 \end{matrix}\right]$
- 求法5：分块乘法，不详细讲解
- 求法2和求法3本质都是看成线性组合
- 行空间：矩阵所有行组成的空间称为行空间

In [1]:
import numpy as np

In [6]:
A = np.array([[1,2,7],[3,4,6],[2,1,3]])
B = np.array([[1,3],[2,1],[1,4]])
C = np.dot(A,B)

In [9]:
print(A)
print(B)
print(C)

[[1 2 7]
 [3 4 6]
 [2 1 3]]
[[1 3]
 [2 1]
 [1 4]]
[[12 33]
 [17 37]
 [ 7 19]]


## 矩阵的逆(方阵)
- 并不是所有矩阵都有逆
- 如果矩阵存在逆，则(左逆)$A^{-1}A=I$,(右逆)$AA^{-1}=I$
- 对于方阵，只要A有逆，放在那边都行。
- 如果A有逆，则称矩阵A可逆的，或非奇异的

### 奇异矩阵（没有逆的情况）
- 奇异矩阵举例：
>- $\left[\begin{matrix} 1&3\\2&6 \end{matrix}\right]$
>- 1)为何以上矩阵没有逆：
>>- 行列式：$1*6-2*3=0$
>>- 可以找到一个非0向量x，使得$Ax=0$这样的矩阵没有逆
>>- 如果其中一列对线性组合毫无贡献，矩阵不可能有逆
>>- 不可逆矩阵、奇异矩阵其列能通过线性组合得到0（就是乘非0向量）

### 求矩阵的逆
- $\left[\begin{matrix} 1&3\\2&7 \end{matrix}\right] \left[\begin{matrix} a&b\\c&d \end{matrix}\right]=\left[\begin{matrix} 1&0\\0&1 \end{matrix}\right]$
- 根据矩阵乘法可以得到两个方程组：$\begin{cases} 1*a+3*c=1 \\ 2*a+7*c=0 \end{cases}$根据以上式子可以解出$\begin{cases} a=7\\c=-2 \end{cases}$,同理可解除c和d$\begin{cases} b=-3\\d=1 \end{cases}$

### 利用高斯消元法求矩阵的逆

- $\left[\begin{array}{lr|lr} 1&3&1&0\\(2)&7&0&1 \end{array}\right] \overbrace{\longrightarrow}^{step 1:col2=col2+col1*-2} \left[\begin{array}{lr|lr} 1&(3)&1&0\\0&1&-2&1 \end{array}\right] \overbrace{\longrightarrow}^{step 2:col1=col1+col2*-3} \left[\begin{array}{lr|lr} 1&0&7&-3\\0&1&-2&1 \end{array}\right] \Longrightarrow A^{-1}=\left[\begin{matrix} 7&-3\\-2&1 \end{matrix}\right]$

- 课程中结尾简单介绍了这个方法可行的原因，并未仔细看